name: 'Pull request cost check'
on:
  workflow_dispatch:
    inputs:
      cost:
        description: 'Pull request hours cost'
        required: false
        type: string
permissions:
  pull-requests: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Check Pull request cost
        id: check_pr_cost
        run: echo "cost=$COST" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          COST: ${{ inputs.cost }}

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: ${{ steps.check_pr_cost.outputs.cost == '' }}
        with:
          header: pr-cost-error
          message: |
            Hey there! üëãüèº

            Pull request cost submission is required for the review.

            URL: https://invoice.holdex.io/prs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.check_pr_cost.outputs.cost != '' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-cost-error
          recreate: true
          message: |
            Pull request cost submitted: $COST hours.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          COST: ${{ inputs.cost }}
